package com.configscanner;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * ISO-3166-1 country list (code + English + Persian names) for the
 * premium-emoji-code manager. Flag emoji is derived from the code.
 */
public class CountryData {

    public static class C {
        public final String code;
        public final String en;
        public final String fa;
        public final String flag;
        C(String code, String en, String fa, String flag) {
            this.code = code; this.en = en; this.fa = fa; this.flag = flag;
        }
    }

    private static final List<C> ALL = new ArrayList<>();
    private static C by(String code) {
        for (C c : ALL) if (c.code.equals(code)) return c;
        return null;
    }

    static {
        ALL.add(new C("AD", "Andorra", "آندورا", GeoChecker.flag("AD")));
        ALL.add(new C("AE", "United Arab Emirates", "امارات متحده عربی", GeoChecker.flag("AE")));
        ALL.add(new C("AF", "Afghanistan", "افغانستان", GeoChecker.flag("AF")));
        ALL.add(new C("AG", "Antigua and Barbuda", "آنتیگوآ و باربودا", GeoChecker.flag("AG")));
        ALL.add(new C("AI", "Anguilla", "آنگویلا", GeoChecker.flag("AI")));
        ALL.add(new C("AL", "Albania", "آلبانی", GeoChecker.flag("AL")));
        ALL.add(new C("AM", "Armenia", "ارمنستان", GeoChecker.flag("AM")));
        ALL.add(new C("AO", "Angola", "آنگولا", GeoChecker.flag("AO")));
        ALL.add(new C("AQ", "Antarctica", "قطب جنوب", GeoChecker.flag("AQ")));
        ALL.add(new C("AR", "Argentina", "آرژانتین", GeoChecker.flag("AR")));
        ALL.add(new C("AS", "American Samoa", "ساموآی آمریکایی", GeoChecker.flag("AS")));
        ALL.add(new C("AT", "Austria", "اتریش", GeoChecker.flag("AT")));
        ALL.add(new C("AU", "Australia", "استرالیا", GeoChecker.flag("AU")));
        ALL.add(new C("AW", "Aruba", "آروبا", GeoChecker.flag("AW")));
        ALL.add(new C("AX", "Aland Islands", "جزایر آلند", GeoChecker.flag("AX")));
        ALL.add(new C("AZ", "Azerbaijan", "آذربایجان", GeoChecker.flag("AZ")));
        ALL.add(new C("BA", "Bosnia and Herzegovina", "بوسنی و هرزگوین", GeoChecker.flag("BA")));
        ALL.add(new C("BB", "Barbados", "باربادوس", GeoChecker.flag("BB")));
        ALL.add(new C("BD", "Bangladesh", "بنگلادش", GeoChecker.flag("BD")));
        ALL.add(new C("BE", "Belgium", "بلژیک", GeoChecker.flag("BE")));
        ALL.add(new C("BF", "Burkina Faso", "بورکینافاسو", GeoChecker.flag("BF")));
        ALL.add(new C("BG", "Bulgaria", "بلغارستان", GeoChecker.flag("BG")));
        ALL.add(new C("BH", "Bahrain", "بحرین", GeoChecker.flag("BH")));
        ALL.add(new C("BI", "Burundi", "بوروندی", GeoChecker.flag("BI")));
        ALL.add(new C("BJ", "Benin", "بنین", GeoChecker.flag("BJ")));
        ALL.add(new C("BL", "Saint Barthelemy", "سنت بارتلومی", GeoChecker.flag("BL")));
        ALL.add(new C("BM", "Bermuda", "برمودا", GeoChecker.flag("BM")));
        ALL.add(new C("BN", "Brunei", "برونئی", GeoChecker.flag("BN")));
        ALL.add(new C("BO", "Bolivia", "بولیوی", GeoChecker.flag("BO")));
        ALL.add(new C("BQ", "Caribbean Netherlands", "هلند کارائیبی", GeoChecker.flag("BQ")));
        ALL.add(new C("BR", "Brazil", "برزیل", GeoChecker.flag("BR")));
        ALL.add(new C("BS", "Bahamas", "باهاما", GeoChecker.flag("BS")));
        ALL.add(new C("BT", "Bhutan", "بوتان", GeoChecker.flag("BT")));
        ALL.add(new C("BV", "Bouvet Island", "جزیره بووه", GeoChecker.flag("BV")));
        ALL.add(new C("BW", "Botswana", "بوتسوانا", GeoChecker.flag("BW")));
        ALL.add(new C("BY", "Belarus", "بلاروس", GeoChecker.flag("BY")));
        ALL.add(new C("BZ", "Belize", "بلیز", GeoChecker.flag("BZ")));
        ALL.add(new C("CA", "Canada", "کانادا", GeoChecker.flag("CA")));
        ALL.add(new C("CC", "Cocos (Keeling) Islands", "جزایر کوکوس", GeoChecker.flag("CC")));
        ALL.add(new C("CD", "DR Congo", "کنگو دموکراتیک", GeoChecker.flag("CD")));
        ALL.add(new C("CF", "Central African Republic", "جمهوری آفریقای مرکزی", GeoChecker.flag("CF")));
        ALL.add(new C("CG", "Congo", "کنگو", GeoChecker.flag("CG")));
        ALL.add(new C("CH", "Switzerland", "سوئیس", GeoChecker.flag("CH")));
        ALL.add(new C("CI", "Ivory Coast", "ساحل عاج", GeoChecker.flag("CI")));
        ALL.add(new C("CK", "Cook Islands", "جزایر کوک", GeoChecker.flag("CK")));
        ALL.add(new C("CL", "Chile", "شیلی", GeoChecker.flag("CL")));
        ALL.add(new C("CM", "Cameroon", "کامرون", GeoChecker.flag("CM")));
        ALL.add(new C("CN", "China", "چین", GeoChecker.flag("CN")));
        ALL.add(new C("CO", "Colombia", "کلمبیا", GeoChecker.flag("CO")));
        ALL.add(new C("CR", "Costa Rica", "کاستاریکا", GeoChecker.flag("CR")));
        ALL.add(new C("CU", "Cuba", "کوبا", GeoChecker.flag("CU")));
        ALL.add(new C("CV", "Cape Verde", "کپ‌ورده", GeoChecker.flag("CV")));
        ALL.add(new C("CW", "Curacao", "کوراچائو", GeoChecker.flag("CW")));
        ALL.add(new C("CX", "Christmas Island", "جزیره کریسمس", GeoChecker.flag("CX")));
        ALL.add(new C("CY", "Cyprus", "قبرص", GeoChecker.flag("CY")));
        ALL.add(new C("CZ", "Czechia", "چک", GeoChecker.flag("CZ")));
        ALL.add(new C("DE", "Germany", "آلمان", GeoChecker.flag("DE")));
        ALL.add(new C("DJ", "Djibouti", "جیبوتی", GeoChecker.flag("DJ")));
        ALL.add(new C("DK", "Denmark", "دانمارک", GeoChecker.flag("DK")));
        ALL.add(new C("DM", "Dominica", "دومینیکا", GeoChecker.flag("DM")));
        ALL.add(new C("DO", "Dominican Republic", "جمهوری دومینیکن", GeoChecker.flag("DO")));
        ALL.add(new C("DZ", "Algeria", "الجزایر", GeoChecker.flag("DZ")));
        ALL.add(new C("EC", "Ecuador", "اکوادور", GeoChecker.flag("EC")));
        ALL.add(new C("EE", "Estonia", "استونی", GeoChecker.flag("EE")));
        ALL.add(new C("EG", "Egypt", "مصر", GeoChecker.flag("EG")));
        ALL.add(new C("EH", "Western Sahara", "صحرای غربی", GeoChecker.flag("EH")));
        ALL.add(new C("ER", "Eritrea", "اریتره", GeoChecker.flag("ER")));
        ALL.add(new C("ES", "Spain", "اسپانیا", GeoChecker.flag("ES")));
        ALL.add(new C("ET", "Ethiopia", "اتیوپی", GeoChecker.flag("ET")));
        ALL.add(new C("FI", "Finland", "فنلاند", GeoChecker.flag("FI")));
        ALL.add(new C("FJ", "Fiji", "فیجی", GeoChecker.flag("FJ")));
        ALL.add(new C("FK", "Falkland Islands", "جزایر فالکلند", GeoChecker.flag("FK")));
        ALL.add(new C("FM", "Micronesia", "میکرونزی", GeoChecker.flag("FM")));
        ALL.add(new C("FO", "Faroe Islands", "جزایر فارو", GeoChecker.flag("FO")));
        ALL.add(new C("FR", "France", "فرانسه", GeoChecker.flag("FR")));
        ALL.add(new C("GA", "Gabon", "گابن", GeoChecker.flag("GA")));
        ALL.add(new C("GB", "United Kingdom", "بریتانیا", GeoChecker.flag("GB")));
        ALL.add(new C("GD", "Grenada", "گرنادا", GeoChecker.flag("GD")));
        ALL.add(new C("GE", "Georgia", "گرجستان", GeoChecker.flag("GE")));
        ALL.add(new C("GF", "French Guiana", "گویان فرانسوی", GeoChecker.flag("GF")));
        ALL.add(new C("GG", "Guernsey", "گرنزی", GeoChecker.flag("GG")));
        ALL.add(new C("GH", "Ghana", "گانا", GeoChecker.flag("GH")));
        ALL.add(new C("GI", "Gibraltar", "جبل‌الطارق", GeoChecker.flag("GI")));
        ALL.add(new C("GL", "Greenland", "گرینلند", GeoChecker.flag("GL")));
        ALL.add(new C("GM", "Gambia", "گامبیا", GeoChecker.flag("GM")));
        ALL.add(new C("GN", "Guinea", "گینه", GeoChecker.flag("GN")));
        ALL.add(new C("GP", "Guadeloupe", "گوادلوپ", GeoChecker.flag("GP")));
        ALL.add(new C("GQ", "Equatorial Guinea", "گینه‌ی معادلی", GeoChecker.flag("GQ")));
        ALL.add(new C("GR", "Greece", "یونان", GeoChecker.flag("GR")));
        ALL.add(new C("GS", "South Georgia", "جرجیای جنوبی", GeoChecker.flag("GS")));
        ALL.add(new C("GT", "Guatemala", "گواتمالا", GeoChecker.flag("GT")));
        ALL.add(new C("GU", "Guam", "گوآم", GeoChecker.flag("GU")));
        ALL.add(new C("GW", "Guinea-Bissau", "گینه‌بیساو", GeoChecker.flag("GW")));
        ALL.add(new C("GY", "Guyana", "گویان", GeoChecker.flag("GY")));
        ALL.add(new C("HK", "Hong Kong", "هنگ‌کنگ", GeoChecker.flag("HK")));
        ALL.add(new C("HM", "Heard and McDonald Islands", "جزایر هرد و مک‌دونالد", GeoChecker.flag("HM")));
        ALL.add(new C("HN", "Honduras", "هندوراس", GeoChecker.flag("HN")));
        ALL.add(new C("HR", "Croatia", "کرواسی", GeoChecker.flag("HR")));
        ALL.add(new C("HT", "Haiti", "هائیتی", GeoChecker.flag("HT")));
        ALL.add(new C("HU", "Hungary", "مجارستان", GeoChecker.flag("HU")));
        ALL.add(new C("ID", "Indonesia", "اندونزی", GeoChecker.flag("ID")));
        ALL.add(new C("IE", "Ireland", "ایرلند", GeoChecker.flag("IE")));
        ALL.add(new C("IL", "Israel", "اسرائیل", GeoChecker.flag("IL")));
        ALL.add(new C("IN", "India", "هند", GeoChecker.flag("IN")));
        ALL.add(new C("IO", "British Indian Ocean Territory", "قلمرو اقیانوس هند بریتانیا", GeoChecker.flag("IO")));
        ALL.add(new C("IQ", "Iraq", "عراق", GeoChecker.flag("IQ")));
        ALL.add(new C("IR", "Iran", "ایران", GeoChecker.flag("IR")));
        ALL.add(new C("IS", "Iceland", "ایسلند", GeoChecker.flag("IS")));
        ALL.add(new C("IT", "Italy", "ایتالیا", GeoChecker.flag("IT")));
        ALL.add(new C("JE", "Jersey", "جِرزی", GeoChecker.flag("JE")));
        ALL.add(new C("JM", "Jamaica", "جامائیکا", GeoChecker.flag("JM")));
        ALL.add(new C("JO", "Jordan", "اردن", GeoChecker.flag("JO")));
        ALL.add(new C("JP", "Japan", "ژاپن", GeoChecker.flag("JP")));
        ALL.add(new C("KE", "Kenya", "کنیا", GeoChecker.flag("KE")));
        ALL.add(new C("KG", "Kyrgyzstan", "قرقیزستان", GeoChecker.flag("KG")));
        ALL.add(new C("KH", "Cambodia", "کمبوجا", GeoChecker.flag("KH")));
        ALL.add(new C("KI", "Kiribati", "کیریباتی", GeoChecker.flag("KI")));
        ALL.add(new C("KM", "Comoros", "کومور", GeoChecker.flag("KM")));
        ALL.add(new C("KN", "Saint Kitts and Nevis", "سنت کیتس و نویس", GeoChecker.flag("KN")));
        ALL.add(new C("KP", "North Korea", "کره شمالی", GeoChecker.flag("KP")));
        ALL.add(new C("KR", "South Korea", "کره جنوبی", GeoChecker.flag("KR")));
        ALL.add(new C("KW", "Kuwait", "کویت", GeoChecker.flag("KW")));
        ALL.add(new C("KZ", "Kazakhstan", "قزاقستان", GeoChecker.flag("KZ")));
        ALL.add(new C("LA", "Laos", "لائوس", GeoChecker.flag("LA")));
        ALL.add(new C("LB", "Lebanon", "لبنان", GeoChecker.flag("LB")));
        ALL.add(new C("LC", "Saint Lucia", "سنت لوسیا", GeoChecker.flag("LC")));
        ALL.add(new C("LI", "Liechtenstein", "لیختن‌اشتاین", GeoChecker.flag("LI")));
        ALL.add(new C("LK", "Sri Lanka", "سری‌لانکا", GeoChecker.flag("LK")));
        ALL.add(new C("LR", "Liberia", "لیبریا", GeoChecker.flag("LR")));
        ALL.add(new C("LS", "Lesotho", "لسوتو", GeoChecker.flag("LS")));
        ALL.add(new C("LT", "Lithuania", "لیتوانی", GeoChecker.flag("LT")));
        ALL.add(new C("LU", "Luxembourg", "لوکسبورگ", GeoChecker.flag("LU")));
        ALL.add(new C("LV", "Latvia", "لتونی", GeoChecker.flag("LV")));
        ALL.add(new C("LY", "Libya", "لیبی", GeoChecker.flag("LY")));
        ALL.add(new C("MA", "Morocco", "مراکش", GeoChecker.flag("MA")));
        ALL.add(new C("MC", "Monaco", "موناکو", GeoChecker.flag("MC")));
        ALL.add(new C("MD", "Moldova", "مولداوی", GeoChecker.flag("MD")));
        ALL.add(new C("ME", "Montenegro", "مونته‌نگرو", GeoChecker.flag("ME")));
        ALL.add(new C("MF", "Saint Martin", "سنت مارتین", GeoChecker.flag("MF")));
        ALL.add(new C("MG", "Madagascar", "ماداگاسکار", GeoChecker.flag("MG")));
        ALL.add(new C("MH", "Marshall Islands", "جزایر مارشال", GeoChecker.flag("MH")));
        ALL.add(new C("MK", "North Macedonia", "مقدونیه شمالی", GeoChecker.flag("MK")));
        ALL.add(new C("ML", "Mali", "مالی", GeoChecker.flag("ML")));
        ALL.add(new C("MM", "Myanmar", "میانمار", GeoChecker.flag("MM")));
        ALL.add(new C("MN", "Mongolia", "مغولستان", GeoChecker.flag("MN")));
        ALL.add(new C("MO", "Macao", "ماکائو", GeoChecker.flag("MO")));
        ALL.add(new C("MP", "Northern Mariana Islands", "جزایر ماریانای شمالی", GeoChecker.flag("MP")));
        ALL.add(new C("MQ", "Martinique", "مارتینیک", GeoChecker.flag("MQ")));
        ALL.add(new C("MR", "Mauritania", "موریتانی", GeoChecker.flag("MR")));
        ALL.add(new C("MS", "Montserrat", "مونتسرات", GeoChecker.flag("MS")));
        ALL.add(new C("MT", "Malta", "مالت", GeoChecker.flag("MT")));
        ALL.add(new C("MU", "Mauritius", "موریس", GeoChecker.flag("MU")));
        ALL.add(new C("MV", "Maldives", "مالدیو", GeoChecker.flag("MV")));
        ALL.add(new C("MW", "Malawi", "مالاوی", GeoChecker.flag("MW")));
        ALL.add(new C("MX", "Mexico", "مکزیک", GeoChecker.flag("MX")));
        ALL.add(new C("MY", "Malaysia", "مالزی", GeoChecker.flag("MY")));
        ALL.add(new C("MZ", "Mozambique", "موزامبیک", GeoChecker.flag("MZ")));
        ALL.add(new C("NA", "Namibia", "نامیبیا", GeoChecker.flag("NA")));
        ALL.add(new C("NC", "New Caledonia", "نیوکالدونی", GeoChecker.flag("NC")));
        ALL.add(new C("NE", "Niger", "نیجر", GeoChecker.flag("NE")));
        ALL.add(new C("NF", "Norfolk Island", "جزیره نورفک", GeoChecker.flag("NF")));
        ALL.add(new C("NG", "Nigeria", "نیجریه", GeoChecker.flag("NG")));
        ALL.add(new C("NI", "Nicaragua", "نیکاراگوئه", GeoChecker.flag("NI")));
        ALL.add(new C("NL", "Netherlands", "هلند", GeoChecker.flag("NL")));
        ALL.add(new C("NO", "Norway", "نروژ", GeoChecker.flag("NO")));
        ALL.add(new C("NP", "Nepal", "نپال", GeoChecker.flag("NP")));
        ALL.add(new C("NR", "Nauru", "نائورو", GeoChecker.flag("NR")));
        ALL.add(new C("NU", "Niue", "نیووی", GeoChecker.flag("NU")));
        ALL.add(new C("NZ", "New Zealand", "نیوزیلند", GeoChecker.flag("NZ")));
        ALL.add(new C("OM", "Oman", "عمان", GeoChecker.flag("OM")));
        ALL.add(new C("PA", "Panama", "پاناما", GeoChecker.flag("PA")));
        ALL.add(new C("PE", "Peru", "پرو", GeoChecker.flag("PE")));
        ALL.add(new C("PF", "French Polynesia", "پلی‌نزی فرانسه", GeoChecker.flag("PF")));
        ALL.add(new C("PG", "Papua New Guinea", "پاپوآ گینه نو", GeoChecker.flag("PG")));
        ALL.add(new C("PH", "Philippines", "فیلیپین", GeoChecker.flag("PH")));
        ALL.add(new C("PK", "Pakistan", "پاکستان", GeoChecker.flag("PK")));
        ALL.add(new C("PL", "Poland", "لهستان", GeoChecker.flag("PL")));
        ALL.add(new C("PM", "Saint Pierre and Miquelon", "سنت پیر و میکلون", GeoChecker.flag("PM")));
        ALL.add(new C("PN", "Pitcairn Islands", "جزایر پیتکرن", GeoChecker.flag("PN")));
        ALL.add(new C("PR", "Puerto Rico", "پورتو ریکو", GeoChecker.flag("PR")));
        ALL.add(new C("PS", "Palestine", "فلسطین", GeoChecker.flag("PS")));
        ALL.add(new C("PT", "Portugal", "پرتغال", GeoChecker.flag("PT")));
        ALL.add(new C("PW", "Palau", "پالائو", GeoChecker.flag("PW")));
        ALL.add(new C("PY", "Paraguay", "پاراگوئه", GeoChecker.flag("PY")));
        ALL.add(new C("QA", "Qatar", "قطر", GeoChecker.flag("QA")));
        ALL.add(new C("RE", "Reunion", "رئونیون", GeoChecker.flag("RE")));
        ALL.add(new C("RO", "Romania", "رومانی", GeoChecker.flag("RO")));
        ALL.add(new C("RS", "Serbia", "صربستان", GeoChecker.flag("RS")));
        ALL.add(new C("RU", "Russia", "روسیه", GeoChecker.flag("RU")));
        ALL.add(new C("RW", "Rwanda", "رواندا", GeoChecker.flag("RW")));
        ALL.add(new C("SA", "Saudi Arabia", "عربستان سعودی", GeoChecker.flag("SA")));
        ALL.add(new C("SB", "Solomon Islands", "جزایر سلیمان", GeoChecker.flag("SB")));
        ALL.add(new C("SC", "Seychelles", "سیشل", GeoChecker.flag("SC")));
        ALL.add(new C("SD", "Sudan", "سودان", GeoChecker.flag("SD")));
        ALL.add(new C("SE", "Sweden", "سوئد", GeoChecker.flag("SE")));
        ALL.add(new C("SG", "Singapore", "سنگاپور", GeoChecker.flag("SG")));
        ALL.add(new C("SH", "Saint Helena", "سنت هلنا", GeoChecker.flag("SH")));
        ALL.add(new C("SI", "Slovenia", "اسلوونی", GeoChecker.flag("SI")));
        ALL.add(new C("SJ", "Svalbard and Jan Mayen", "سوالبارد", GeoChecker.flag("SJ")));
        ALL.add(new C("SK", "Slovakia", "اسلواکی", GeoChecker.flag("SK")));
        ALL.add(new C("SL", "Sierra Leone", "سیرالئون", GeoChecker.flag("SL")));
        ALL.add(new C("SM", "San Marino", "سان‌مارینو", GeoChecker.flag("SM")));
        ALL.add(new C("SN", "Senegal", "سنگال", GeoChecker.flag("SN")));
        ALL.add(new C("SO", "Somalia", "سومالی", GeoChecker.flag("SO")));
        ALL.add(new C("SR", "Suriname", "سورینام", GeoChecker.flag("SR")));
        ALL.add(new C("SS", "South Sudan", "سودان جنوبی", GeoChecker.flag("SS")));
        ALL.add(new C("ST", "Sao Tome and Principe", "سائوتومه و پرنسیپ", GeoChecker.flag("ST")));
        ALL.add(new C("SV", "El Salvador", "السالوادور", GeoChecker.flag("SV")));
        ALL.add(new C("SX", "Sint Maarten", "سینت مارتن", GeoChecker.flag("SX")));
        ALL.add(new C("SY", "Syria", "سوریه", GeoChecker.flag("SY")));
        ALL.add(new C("SZ", "Eswatini", "اسواتینی", GeoChecker.flag("SZ")));
        ALL.add(new C("TC", "Turks and Caicos Islands", "جزایر تورکس و کائیکوس", GeoChecker.flag("TC")));
        ALL.add(new C("TD", "Chad", "چاد", GeoChecker.flag("TD")));
        ALL.add(new C("TF", "French Southern Lands", "سرزمین‌های جنوبی فرانسه", GeoChecker.flag("TF")));
        ALL.add(new C("TG", "Togo", "توگو", GeoChecker.flag("TG")));
        ALL.add(new C("TH", "Thailand", "تایلند", GeoChecker.flag("TH")));
        ALL.add(new C("TJ", "Tajikistan", "تاجیکستان", GeoChecker.flag("TJ")));
        ALL.add(new C("TK", "Tokelau", "توکلائو", GeoChecker.flag("TK")));
        ALL.add(new C("TL", "Timor-Leste", "تیمور شرقی", GeoChecker.flag("TL")));
        ALL.add(new C("TM", "Turkmenistan", "ترکمنستان", GeoChecker.flag("TM")));
        ALL.add(new C("TN", "Tunisia", "تونس", GeoChecker.flag("TN")));
        ALL.add(new C("TO", "Tonga", "تونگا", GeoChecker.flag("TO")));
        ALL.add(new C("TR", "Turkey", "ترکیه", GeoChecker.flag("TR")));
        ALL.add(new C("TT", "Trinidad and Tobago", "ترینیداد و توباگو", GeoChecker.flag("TT")));
        ALL.add(new C("TV", "Tuvalu", "توالو", GeoChecker.flag("TV")));
        ALL.add(new C("TW", "Taiwan", "تایوان", GeoChecker.flag("TW")));
        ALL.add(new C("TZ", "Tanzania", "تانزانیا", GeoChecker.flag("TZ")));
        ALL.add(new C("UA", "Ukraine", "اوکراین", GeoChecker.flag("UA")));
        ALL.add(new C("UG", "Uganda", "اوگاندا", GeoChecker.flag("UG")));
        ALL.add(new C("UM", "US Minor Outlying Islands", "جزایر کوچک متفرقه آمریکا", GeoChecker.flag("UM")));
        ALL.add(new C("US", "United States", "ایالات متحده", GeoChecker.flag("US")));
        ALL.add(new C("UY", "Uruguay", "اروگوئه", GeoChecker.flag("UY")));
        ALL.add(new C("UZ", "Uzbekistan", "ازبکستان", GeoChecker.flag("UZ")));
        ALL.add(new C("VA", "Vatican City", "واتیکان", GeoChecker.flag("VA")));
        ALL.add(new C("VC", "Saint Vincent and the Grenadines", "سنت وینسنت و گرنادین", GeoChecker.flag("VC")));
        ALL.add(new C("VE", "Venezuela", "ونزوئلا", GeoChecker.flag("VE")));
        ALL.add(new C("VG", "British Virgin Islands", "جزایر ویرجین بریتانیا", GeoChecker.flag("VG")));
        ALL.add(new C("VI", "US Virgin Islands", "جزایر ویرجین آمریکا", GeoChecker.flag("VI")));
        ALL.add(new C("VN", "Vietnam", "ویتنام", GeoChecker.flag("VN")));
        ALL.add(new C("VU", "Vanuatu", "وانواتو", GeoChecker.flag("VU")));
        ALL.add(new C("WF", "Wallis and Futuna", "والیس و فوتونا", GeoChecker.flag("WF")));
        ALL.add(new C("WS", "Samoa", "ساموآ", GeoChecker.flag("WS")));
        ALL.add(new C("XK", "Kosovo", "کوزوو", GeoChecker.flag("XK")));
        ALL.add(new C("YE", "Yemen", "یمن", GeoChecker.flag("YE")));
        ALL.add(new C("YT", "Mayotte", "مایوت", GeoChecker.flag("YT")));
        ALL.add(new C("ZA", "South Africa", "آفریقای جنوبی", GeoChecker.flag("ZA")));
        ALL.add(new C("ZM", "Zambia", "زامبیا", GeoChecker.flag("ZM")));
        ALL.add(new C("ZW", "Zimbabwe", "زیمبابوه", GeoChecker.flag("ZW")));
    }

    /** All countries, sorted by English name. */
    public static List<C> all() {
        List<C> l = new ArrayList<>(ALL);
        Collections.sort(l, (a, b) -> a.en.compareToIgnoreCase(b.en));
        return l;
    }

    public static C byCode(String code) {
        if (code == null || code.length() != 2) return null;
        return by(code.toUpperCase());
    }
}
